/*HEADER**********************************************************************
*
* Copyright 2013 Freescale Semiconductor, Inc.
*
* This software is owned or controlled by Freescale Semiconductor.
* Use of this software is governed by the Freescale MQX RTOS License
* distributed with this Material.
* See the MQX_RTOS_LICENSE file distributed for more details.
*
* Brief License Summary:
* This software is provided in source form for you to use free of charge,
* but it is not open source software. You are allowed to use this software
* but you cannot redistribute it or derivative works of it in source form.
* The software may be used only in connection with a product containing
* a Freescale microprocessor, microcontroller, or digital signal processor.
* See license agreement file for full license terms including other
* restrictions.
*****************************************************************************
*
* Comments:
*
*   Clock name enumeration definition for Vybrid
*
*
*END************************************************************************/

#ifndef __bsp_clk_name_h__
#define __bsp_clk_name_h__

typedef enum _clockNames {
    CLK_FXOSC,
    CLK_FIRC,
    CLK_SXOSC,
    CLK_SIRC,
    CLK_FXOSC_DIV,
    CLK_SIRC_DIV,
    CLK_FAST,
    CLK_SLOW,
    CLK_CLK_24M_IRC,
    CLK_LPRC,
    CLK_LFSR,
    CLK_PLL1,
    CLK_PLL1_PFD1,
    CLK_PLL1_PFD2,
    CLK_PLL1_PFD3,
    CLK_PLL1_PFD4,
    CLK_PLL2,
    CLK_PLL2_PFD1,
    CLK_PLL2_PFD2,
    CLK_PLL2_PFD3,
    CLK_PLL2_PFD4,
    CLK_PLL3,
    CLK_PLL3_PFD1,
    CLK_PLL3_PFD2,
    CLK_PLL3_PFD3,
    CLK_PLL3_PFD4,
    CLK_PLL3_DIV,
    CLK_PLL4,
    CLK_PLL4_DIV,
    CLK_PLL5,
    CLK_PLL5_DIV,
    CLK_PLL6,
    CLK_PLL6_DIV,
    CLK_PLL7,
    CLK_PLL1_PFD,
    CLK_PLL2_PFD,
    CLK_SYS,
    CLK_CA5_CORE,
    CLK_PLATFORM_BUS,
    CLK_FLEXBUS,
    CLK_IPS_IPG,
    CLK_DRAMC,
    CLK_AUDIO_EXT,
    CLK_FLEXCAN0,
    CLK_FLEXCAN1,
    CLK_FTM0_EXT,
    CLK_FTM1_EXT,
    CLK_FTM2_EXT,
    CLK_FTM3_EXT,
    CLK_FTM0_FIX,
    CLK_FTM1_FIX,
    CLK_FTM2_FIX,
    CLK_FTM3_FIX,
    CLK_NFC,
    CLK_QSPI0,
    CLK_QSPI1,
    CLK_ENET_EXT,
    CLK_ENET_TS_EXT,
    CLK_ENET_RMII,
    CLK_USBC0,
    CLK_USBC1,
    CLK_ENET_TS,
    CLK_ESDHC0,
    CLK_ESDHC1,
    CLK_DCU_PIXEL0,
    CLK_DCU_PIXEL1,
    CLK_DCU0,
    CLK_DCU1,
    CLK_SPDIF_EXT,
    CLK_MLB_EXT,
    CLK_ESAI_HCKT_EXT,
    CLK_SAI0TX_BCLK_EXT,
    CLK_SAI3_BCLK_EXT,
    CLK_ESAI,
    CLK_SAI0,
    CLK_SAI1,
    CLK_SAI2,
    CLK_SAI3,
    CLK_VIDEO_ADC,
    CLK_GPU,
    CLK_SWO,
    CLK_TRACE,
    CLK_USB0,
    CLK_USB1,
    CLK_SPDIF,
    CLK_DAP,
    CLK_DMA_MUX0,
    CLK_DMA_MUX1,
    CLK_DMA_MUX2,
    CLK_DMA_MUX3,
    CLK_DMA0_TCD,
    CLK_DMA1_TCD,
    CLK_DMA0,
    CLK_DMA1,
    CLK_UART0,
    CLK_UART1,
    CLK_UART2,
    CLK_UART3,
    CLK_UART4,
    CLK_UART5,
    CLK_SPI0,
    CLK_SPI1,
    CLK_SPI2,
    CLK_SPI3,
    CLK_CRC,
    CLK_PDB,
    CLK_PIT,
    CLK_FTM0,
    CLK_FTM1,
    CLK_FTM2,
    CLK_FTM3,
    CLK_ADC0,
    CLK_ADC1,
    CLK_TCON0,
    CLK_TCON1,
    CLK_WDOG_A5,
    CLK_WDOG_M4,
    CLK_LPTMR,
    CLK_RLE,
    CLK_IOMUXC,
    CLK_PORTA_MULT,
    CLK_PORTB_MULT,
    CLK_PORTC_MULT,
    CLK_PORTD_MULT,
    CLK_PORTE_MULT,
    CLK_ANADIG,
    CLK_SCSC,
    CLK_ASRC,
    CLK_EWM,
    CLK_I2C0,
    CLK_I2C1,
    CLK_I2C2,
    CLK_I2C3,
    CLK_WKUP,
    CLK_CCM,
    CLK_GPC,
    CLK_VREG_DIG,
    CLK_CMU,
    CLK_OTP,
    CLK_SLCD,
    CLK_VIDEO_DECODER,
    CLK_VIU,
    CLK_DAC0,
    CLK_DAC1,
    CLK_ENET_MAC0,
    CLK_ENET_MAC1,
    CLK_ENET_L2_SW,
    CLK_MSCM,
    CLK_CA5_SCU_GIC,
    CLK_CA5_INTD,
    CLK_CA5_L2C,
    CLK_NIC0,
    CLK_NIC1,
    CLK_NIC2,
    CLK_NIC3,
    CLK_NIC4,
    CLK_NIC5,
    CLK_NIC6,
    CLK_NIC7,
    CLK_SEMA4,
    CLK_CA5_DBG,
    CLK_CA5_PMU,
    CLK_CA5_ETM,
    CLK_CA5_ROMTABLE,
    CLK_CA5_CTI,
    CLK_CA5_ITM,
    CLK_CA5_ETB,
    CLK_CA5_FUNNEL,
    CLK_PLTF_TCTL,
    CLK_PLTF_TCTU,
    CLK_PLTF_FUNNEL,
    CLK_PLTF_SWO,
    CLK_MAX
} CLOCK_NAME;


#endif
