/*HEADER**********************************************************************
*
* Copyright 2013 Freescale Semiconductor, Inc.
*
* This software is owned or controlled by Freescale Semiconductor.
* Use of this software is governed by the Freescale MQX RTOS License
* distributed with this Material.
* See the MQX_RTOS_LICENSE file distributed for more details.
*
* Brief License Summary:
* This software is provided in source form for you to use free of charge,
* but it is not open source software. You are allowed to use this software
* but you cannot redistribute it or derivative works of it in source form.
* The software may be used only in connection with a product containing
* a Freescale microprocessor, microcontroller, or digital signal processor.
* See license agreement file for full license terms including other
* restrictions.
*****************************************************************************
*
* Comments:
*
*   Header file for vybrid clock nodes implementation
*
*
*END************************************************************************/

#ifndef __bsp_clock_nodes_impl_h__
#define __bsp_clock_nodes_impl_h__

#include "bsp_clk_nodes.h"

uint8_t is_physically_open_fxosc(void);
uint8_t is_physically_open_firc(void);
uint8_t is_physically_open_sxosc(void);
uint8_t is_physically_open_sirc(void);
uint8_t is_physically_open_fxosc_div(void);
uint8_t is_physically_open_sirc_div(void);
uint8_t is_physically_open_fast(void);
uint8_t is_physically_open_slow(void);
uint8_t is_physically_open_clk_24m_irc(void);
uint8_t is_physically_open_lprc(void);
uint8_t is_physically_open_lfsr(void);
uint8_t is_physically_open_pll1(void);
uint8_t is_physically_open_pll1_pfd1(void);
uint8_t is_physically_open_pll1_pfd2(void);
uint8_t is_physically_open_pll1_pfd3(void);
uint8_t is_physically_open_pll1_pfd4(void);
uint8_t is_physically_open_pll2(void);
uint8_t is_physically_open_pll2_pfd1(void);
uint8_t is_physically_open_pll2_pfd2(void);
uint8_t is_physically_open_pll2_pfd3(void);
uint8_t is_physically_open_pll2_pfd4(void);
uint8_t is_physically_open_pll3(void);
uint8_t is_physically_open_pll3_pfd1(void);
uint8_t is_physically_open_pll3_pfd2(void);
uint8_t is_physically_open_pll3_pfd3(void);
uint8_t is_physically_open_pll3_pfd4(void);
uint8_t is_physically_open_pll3_div(void);
uint8_t is_physically_open_pll4(void);
uint8_t is_physically_open_pll4_div(void);
uint8_t is_physically_open_pll5(void);
uint8_t is_physically_open_pll5_div(void);
uint8_t is_physically_open_pll6(void);
uint8_t is_physically_open_pll6_div(void);
uint8_t is_physically_open_pll7(void);
uint8_t is_physically_open_pll1_pfd(void);
uint8_t is_physically_open_pll2_pfd(void);
uint8_t is_physically_open_sys(void);
uint8_t is_physically_open_ca5_core(void);
uint8_t is_physically_open_platform_bus_cm4_core(void);
uint8_t is_physically_open_flexbus(void);
uint8_t is_physically_open_ips_ipg(void);
uint8_t is_physically_open_dramc(void);
uint8_t is_physically_open_audio_ext(void);
uint8_t is_physically_open_flexcan0(void);
uint8_t is_physically_open_flexcan1(void);
uint8_t is_physically_open_ftm0_ext(void);
uint8_t is_physically_open_ftm1_ext(void);
uint8_t is_physically_open_ftm2_ext(void);
uint8_t is_physically_open_ftm3_ext(void);
uint8_t is_physically_open_ftm0_fix(void);
uint8_t is_physically_open_ftm1_fix(void);
uint8_t is_physically_open_ftm2_fix(void);
uint8_t is_physically_open_ftm3_fix(void);
uint8_t is_physically_open_nfc(void);
uint8_t is_physically_open_qspi0(void);
uint8_t is_physically_open_qspi1(void);
uint8_t is_physically_open_enet_ext(void);
uint8_t is_physically_open_enet_rmii(void);
uint8_t is_physically_open_enet_ts(void);
uint8_t is_physically_open_esdhc0(void);
uint8_t is_physically_open_esdhc1(void);
uint8_t is_physically_open_dcu_pixel0(void);
uint8_t is_physically_open_dcu_pixel1(void);
uint8_t is_physically_open_dcu0(void);
uint8_t is_physically_open_dcu1(void);
uint8_t is_physically_open_spdif_ext(void);
uint8_t is_physically_open_esai(void);
uint8_t is_physically_open_sai0(void);
uint8_t is_physically_open_sai1(void);
uint8_t is_physically_open_sai2(void);
uint8_t is_physically_open_sai3(void);
uint8_t is_physically_open_video_adc(void);
uint8_t is_physically_open_gpu(void);
uint8_t is_physically_open_swo(void);
uint8_t is_physically_open_trace(void);
uint8_t is_physically_open_usb0(void);
uint8_t is_physically_open_usb1(void);
uint8_t is_physically_open_spdif(void);
uint8_t is_physically_open_dap(void);
uint8_t is_physically_open_dma_mux0(void);
uint8_t is_physically_open_dma_mux1(void);
uint8_t is_physically_open_dma_mux2(void);
uint8_t is_physically_open_dma_mux3(void);
uint8_t is_physically_open_dma0_tcd(void);
uint8_t is_physically_open_dma1_tcd(void);
uint8_t is_physically_open_dma0(void);
uint8_t is_physically_open_dma1(void);
uint8_t is_physically_open_uart0(void);
uint8_t is_physically_open_uart1(void);
uint8_t is_physically_open_uart2(void);
uint8_t is_physically_open_uart3(void);
uint8_t is_physically_open_uart4(void);
uint8_t is_physically_open_uart5(void);
uint8_t is_physically_open_spi0(void);
uint8_t is_physically_open_spi1(void);
uint8_t is_physically_open_spi2(void);
uint8_t is_physically_open_spi3(void);
uint8_t is_physically_open_crc(void);
uint8_t is_physically_open_usbc0(void);
uint8_t is_physically_open_usbc1(void);
uint8_t is_physically_open_pdb(void);
uint8_t is_physically_open_pit(void);
uint8_t is_physically_open_ftm(void);
uint8_t is_physically_open_adc0(void);
uint8_t is_physically_open_adc1(void);
uint8_t is_physically_open_tcon0(void);
uint8_t is_physically_open_tcon1(void);
uint8_t is_physically_open_wdog_a5(void);
uint8_t is_physically_open_wdog_m4(void);
uint8_t is_physically_open_lptmr(void);
uint8_t is_physically_open_rle(void);
uint8_t is_physically_open_iomuxc(void);
uint8_t is_physically_open_porta_mult(void);
uint8_t is_physically_open_portb_mult(void);
uint8_t is_physically_open_portc_mult(void);
uint8_t is_physically_open_portd_mult(void);
uint8_t is_physically_open_porte_mult(void);
uint8_t is_physically_open_anadig(void);
uint8_t is_physically_open_scsc(void);
uint8_t is_physically_open_asrc(void);
uint8_t is_physically_open_ewm(void);
uint8_t is_physically_open_i2c0(void);
uint8_t is_physically_open_i2c1(void);
uint8_t is_physically_open_i2c2(void);
uint8_t is_physically_open_i2c3(void);
uint8_t is_physically_open_wkup(void);
uint8_t is_physically_open_ccm(void);
uint8_t is_physically_open_gpc(void);
uint8_t is_physically_open_vreg_dig(void);
uint8_t is_physically_open_cmu(void);
uint8_t is_physically_open_otp(void);
uint8_t is_physically_open_slcd(void);
uint8_t is_physically_open_video_decoder(void);
uint8_t is_physically_open_viu(void);
uint8_t is_physically_open_dac0(void);
uint8_t is_physically_open_dac1(void);
uint8_t is_physically_open_enet_mac_ieee1588_timer0(void);
uint8_t is_physically_open_enet_mac_ieee1588_timer1(void);
uint8_t is_physically_open_enet_l2_sw(void);
uint8_t is_physically_open_mscm(void);
uint8_t is_physically_open_ca5_scu_gic(void);
uint8_t is_physically_open_ca5_intd(void);
uint8_t is_physically_open_ca5_l2c(void);
uint8_t is_physically_open_nic0(void);
uint8_t is_physically_open_nic1(void);
uint8_t is_physically_open_nic2(void);
uint8_t is_physically_open_nic3(void);
uint8_t is_physically_open_nic4(void);
uint8_t is_physically_open_nic5(void);
uint8_t is_physically_open_nic6(void);
uint8_t is_physically_open_nic7(void);
uint8_t is_physically_open_sema4(void);
uint8_t is_physically_open_ca5_dbg(void);
uint8_t is_physically_open_ca5_pmu(void);
uint8_t is_physically_open_ca5_etm(void);
uint8_t is_physically_open_ca5_romtable(void);
uint8_t is_physically_open_ca5_cti(void);
uint8_t is_physically_open_ca5_itm(void);
uint8_t is_physically_open_ca5_etb(void);
uint8_t is_physically_open_ca5_funnel(void);
uint8_t is_physically_open_pltf_tctl(void);
uint8_t is_physically_open_pltf_tctu(void);
uint8_t is_physically_open_pltf_funnel(void);
uint8_t is_physically_open_pltf_swo(void);
uint8_t is_physically_open_enet_ts_ext(void);
uint8_t is_physically_open_mlb_ext(void);
uint8_t is_physically_open_esai_ext(void);
uint8_t is_physically_open_sai0_ext(void);
uint8_t is_physically_open_sai3_ext(void);
uint8_t is_physically_open_ftm0(void);
uint8_t is_physically_open_ftm1(void);
uint8_t is_physically_open_ftm2(void);
uint8_t is_physically_open_ftm3(void);

P_CLK_NODE_T get_parent_fxosc(void);
P_CLK_NODE_T get_parent_firc(void);
P_CLK_NODE_T get_parent_sxosc(void);
P_CLK_NODE_T get_parent_sirc(void);
P_CLK_NODE_T get_parent_fxosc_div(void);
P_CLK_NODE_T get_parent_sirc_div(void);
P_CLK_NODE_T get_parent_fast(void);
P_CLK_NODE_T get_parent_slow(void);
P_CLK_NODE_T get_parent_clk_24m_irc(void);
P_CLK_NODE_T get_parent_lprc(void);
P_CLK_NODE_T get_parent_lfsr(void);
P_CLK_NODE_T get_parent_pll1(void);
P_CLK_NODE_T get_parent_pll1_pfd1(void);
P_CLK_NODE_T get_parent_pll1_pfd2(void);
P_CLK_NODE_T get_parent_pll1_pfd3(void);
P_CLK_NODE_T get_parent_pll1_pfd4(void);
P_CLK_NODE_T get_parent_pll2(void);
P_CLK_NODE_T get_parent_pll2_pfd1(void);
P_CLK_NODE_T get_parent_pll2_pfd2(void);
P_CLK_NODE_T get_parent_pll2_pfd3(void);
P_CLK_NODE_T get_parent_pll2_pfd4(void);
P_CLK_NODE_T get_parent_pll3(void);
P_CLK_NODE_T get_parent_pll3_pfd1(void);
P_CLK_NODE_T get_parent_pll3_pfd2(void);
P_CLK_NODE_T get_parent_pll3_pfd3(void);
P_CLK_NODE_T get_parent_pll3_pfd4(void);
P_CLK_NODE_T get_parent_pll3_div(void);
P_CLK_NODE_T get_parent_pll4(void);
P_CLK_NODE_T get_parent_pll4_div(void);
P_CLK_NODE_T get_parent_pll5(void);
P_CLK_NODE_T get_parent_pll5_div(void);
P_CLK_NODE_T get_parent_pll6(void);
P_CLK_NODE_T get_parent_pll6_div(void);
P_CLK_NODE_T get_parent_pll7(void);
P_CLK_NODE_T get_parent_pll1_pfd(void);
P_CLK_NODE_T get_parent_pll2_pfd(void);
P_CLK_NODE_T get_parent_sys(void);
P_CLK_NODE_T get_parent_ca5_core(void);
P_CLK_NODE_T get_parent_platform_bus_cm4_core(void);
P_CLK_NODE_T get_parent_flexbus(void);
P_CLK_NODE_T get_parent_ips_ipg(void);
P_CLK_NODE_T get_parent_dramc(void);
P_CLK_NODE_T get_parent_audio_ext(void);
P_CLK_NODE_T get_parent_flexcan0(void);
P_CLK_NODE_T get_parent_flexcan1(void);
P_CLK_NODE_T get_parent_ftm0_ext(void);
P_CLK_NODE_T get_parent_ftm1_ext(void);
P_CLK_NODE_T get_parent_ftm2_ext(void);
P_CLK_NODE_T get_parent_ftm3_ext(void);
P_CLK_NODE_T get_parent_ftm0_fix(void);
P_CLK_NODE_T get_parent_ftm1_fix(void);
P_CLK_NODE_T get_parent_ftm2_fix(void);
P_CLK_NODE_T get_parent_ftm3_fix(void);
P_CLK_NODE_T get_parent_nfc(void);
P_CLK_NODE_T get_parent_qspi0(void);
P_CLK_NODE_T get_parent_qspi1(void);
P_CLK_NODE_T get_parent_enet_ext(void);
P_CLK_NODE_T get_parent_enet_rmii(void);
P_CLK_NODE_T get_parent_enet_ts(void);
P_CLK_NODE_T get_parent_esdhc0(void);
P_CLK_NODE_T get_parent_esdhc1(void);
P_CLK_NODE_T get_parent_dcu_pixel0(void);
P_CLK_NODE_T get_parent_dcu_pixel1(void);
P_CLK_NODE_T get_parent_dcu0(void);
P_CLK_NODE_T get_parent_dcu1(void);
P_CLK_NODE_T get_parent_spdif_ext(void);
P_CLK_NODE_T get_parent_esai(void);
P_CLK_NODE_T get_parent_sai0(void);
P_CLK_NODE_T get_parent_sai1(void);
P_CLK_NODE_T get_parent_sai2(void);
P_CLK_NODE_T get_parent_sai3(void);
P_CLK_NODE_T get_parent_video_adc(void);
P_CLK_NODE_T get_parent_gpu(void);
P_CLK_NODE_T get_parent_swo(void);
P_CLK_NODE_T get_parent_trace(void);
P_CLK_NODE_T get_parent_usb0(void);
P_CLK_NODE_T get_parent_usb1(void);
P_CLK_NODE_T get_parent_spdif(void);
P_CLK_NODE_T get_parent_dap(void);
P_CLK_NODE_T get_parent_dma_mux0(void);
P_CLK_NODE_T get_parent_dma_mux1(void);
P_CLK_NODE_T get_parent_dma_mux2(void);
P_CLK_NODE_T get_parent_dma_mux3(void);
P_CLK_NODE_T get_parent_dma0_tcd(void);
P_CLK_NODE_T get_parent_dma1_tcd(void);
P_CLK_NODE_T get_parent_dma0(void);
P_CLK_NODE_T get_parent_dma1(void);
P_CLK_NODE_T get_parent_uart0(void);
P_CLK_NODE_T get_parent_uart1(void);
P_CLK_NODE_T get_parent_uart2(void);
P_CLK_NODE_T get_parent_uart3(void);
P_CLK_NODE_T get_parent_uart4(void);
P_CLK_NODE_T get_parent_uart5(void);
P_CLK_NODE_T get_parent_spi0(void);
P_CLK_NODE_T get_parent_spi1(void);
P_CLK_NODE_T get_parent_spi2(void);
P_CLK_NODE_T get_parent_spi3(void);
P_CLK_NODE_T get_parent_crc(void);
P_CLK_NODE_T get_parent_usbc0(void);
P_CLK_NODE_T get_parent_usbc1(void);
P_CLK_NODE_T get_parent_pdb(void);
P_CLK_NODE_T get_parent_pit(void);
P_CLK_NODE_T get_parent_ftm(void);
P_CLK_NODE_T get_parent_adc0(void);
P_CLK_NODE_T get_parent_adc1(void);
P_CLK_NODE_T get_parent_tcon0(void);
P_CLK_NODE_T get_parent_tcon1(void);
P_CLK_NODE_T get_parent_wdog_a5(void);
P_CLK_NODE_T get_parent_wdog_m4(void);
P_CLK_NODE_T get_parent_lptmr(void);
P_CLK_NODE_T get_parent_rle(void);
P_CLK_NODE_T get_parent_iomuxc(void);
P_CLK_NODE_T get_parent_porta_mult(void);
P_CLK_NODE_T get_parent_portb_mult(void);
P_CLK_NODE_T get_parent_portc_mult(void);
P_CLK_NODE_T get_parent_portd_mult(void);
P_CLK_NODE_T get_parent_porte_mult(void);
P_CLK_NODE_T get_parent_anadig(void);
P_CLK_NODE_T get_parent_scsc(void);
P_CLK_NODE_T get_parent_asrc(void);
P_CLK_NODE_T get_parent_ewm(void);
P_CLK_NODE_T get_parent_i2c0(void);
P_CLK_NODE_T get_parent_i2c1(void);
P_CLK_NODE_T get_parent_i2c2(void);
P_CLK_NODE_T get_parent_i2c3(void);
P_CLK_NODE_T get_parent_wkup(void);
P_CLK_NODE_T get_parent_ccm(void);
P_CLK_NODE_T get_parent_gpc(void);
P_CLK_NODE_T get_parent_vreg_dig(void);
P_CLK_NODE_T get_parent_cmu(void);
P_CLK_NODE_T get_parent_otp(void);
P_CLK_NODE_T get_parent_slcd(void);
P_CLK_NODE_T get_parent_video_decoder(void);
P_CLK_NODE_T get_parent_viu(void);
P_CLK_NODE_T get_parent_dac0(void);
P_CLK_NODE_T get_parent_dac1(void);
P_CLK_NODE_T get_parent_enet_mac_ieee1588_timer0(void);
P_CLK_NODE_T get_parent_enet_mac_ieee1588_timer1(void);
P_CLK_NODE_T get_parent_enet_l2_sw(void);
P_CLK_NODE_T get_parent_mscm(void);
P_CLK_NODE_T get_parent_ca5_scu_gic(void);
P_CLK_NODE_T get_parent_ca5_intd(void);
P_CLK_NODE_T get_parent_ca5_l2c(void);
P_CLK_NODE_T get_parent_nic0(void);
P_CLK_NODE_T get_parent_nic1(void);
P_CLK_NODE_T get_parent_nic2(void);
P_CLK_NODE_T get_parent_nic3(void);
P_CLK_NODE_T get_parent_nic4(void);
P_CLK_NODE_T get_parent_nic5(void);
P_CLK_NODE_T get_parent_nic6(void);
P_CLK_NODE_T get_parent_nic7(void);
P_CLK_NODE_T get_parent_sema4(void);
P_CLK_NODE_T get_parent_ca5_dbg(void);
P_CLK_NODE_T get_parent_ca5_pmu(void);
P_CLK_NODE_T get_parent_ca5_etm(void);
P_CLK_NODE_T get_parent_ca5_romtable(void);
P_CLK_NODE_T get_parent_ca5_cti(void);
P_CLK_NODE_T get_parent_ca5_itm(void);
P_CLK_NODE_T get_parent_ca5_etb(void);
P_CLK_NODE_T get_parent_ca5_funnel(void);
P_CLK_NODE_T get_parent_pltf_tctl(void);
P_CLK_NODE_T get_parent_pltf_tctu(void);
P_CLK_NODE_T get_parent_pltf_funnel(void);
P_CLK_NODE_T get_parent_pltf_swo(void);
P_CLK_NODE_T get_parent_enet_ts_ext(void);
P_CLK_NODE_T get_parent_mlb_ext(void);
P_CLK_NODE_T get_parent_esai_ext(void);
P_CLK_NODE_T get_parent_sai0_ext(void);
P_CLK_NODE_T get_parent_sai3_ext(void);
P_CLK_NODE_T get_parent_ftm0(void);
P_CLK_NODE_T get_parent_ftm1(void);
P_CLK_NODE_T get_parent_ftm2(void);
P_CLK_NODE_T get_parent_ftm3(void);

uint8_t set_parent_fxosc(P_CLK_NODE_T parent);
uint8_t set_parent_firc(P_CLK_NODE_T parent);
uint8_t set_parent_sxosc(P_CLK_NODE_T parent);
uint8_t set_parent_sirc(P_CLK_NODE_T parent);
uint8_t set_parent_fast(P_CLK_NODE_T parent);
uint8_t set_parent_slow(P_CLK_NODE_T parent);
uint8_t set_parent_clk_24m_irc(P_CLK_NODE_T parent);
uint8_t set_parent_lprc(P_CLK_NODE_T parent);
uint8_t set_parent_lfsr(P_CLK_NODE_T parent);
uint8_t set_parent_pll1(P_CLK_NODE_T parent);
uint8_t set_parent_pll1_pfd1(P_CLK_NODE_T parent);
uint8_t set_parent_pll1_pfd2(P_CLK_NODE_T parent);
uint8_t set_parent_pll1_pfd3(P_CLK_NODE_T parent);
uint8_t set_parent_pll1_pfd4(P_CLK_NODE_T parent);
uint8_t set_parent_pll2(P_CLK_NODE_T parent);
uint8_t set_parent_pll2_pfd1(P_CLK_NODE_T parent);
uint8_t set_parent_pll2_pfd2(P_CLK_NODE_T parent);
uint8_t set_parent_pll2_pfd3(P_CLK_NODE_T parent);
uint8_t set_parent_pll2_pfd4(P_CLK_NODE_T parent);
uint8_t set_parent_pll3(P_CLK_NODE_T parent);
uint8_t set_parent_pll3_pfd1(P_CLK_NODE_T parent);
uint8_t set_parent_pll3_pfd2(P_CLK_NODE_T parent);
uint8_t set_parent_pll3_pfd3(P_CLK_NODE_T parent);
uint8_t set_parent_pll3_pfd4(P_CLK_NODE_T parent);
uint8_t set_parent_pll3_div(P_CLK_NODE_T parent);
uint8_t set_parent_pll4(P_CLK_NODE_T parent);
uint8_t set_parent_pll4_div(P_CLK_NODE_T parent);
uint8_t set_parent_pll5(P_CLK_NODE_T parent);
uint8_t set_parent_pll5_div(P_CLK_NODE_T parent);
uint8_t set_parent_pll6(P_CLK_NODE_T parent);
uint8_t set_parent_pll6_div(P_CLK_NODE_T parent);
uint8_t set_parent_pll7(P_CLK_NODE_T parent);
uint8_t set_parent_pll1_pfd(P_CLK_NODE_T parent);
uint8_t set_parent_pll2_pfd(P_CLK_NODE_T parent);
uint8_t set_parent_sys(P_CLK_NODE_T parent);
uint8_t set_parent_ca5_core(P_CLK_NODE_T parent);
uint8_t set_parent_platform_bus_cm4_core(P_CLK_NODE_T parent);
uint8_t set_parent_flexbus(P_CLK_NODE_T parent);
uint8_t set_parent_ips_ipg(P_CLK_NODE_T parent);
uint8_t set_parent_dramc(P_CLK_NODE_T parent);
uint8_t set_parent_audio_ext(P_CLK_NODE_T parent);
uint8_t set_parent_flexcan0(P_CLK_NODE_T parent);
uint8_t set_parent_flexcan1(P_CLK_NODE_T parent);
uint8_t set_parent_ftm0_ext(P_CLK_NODE_T parent);
uint8_t set_parent_ftm1_ext(P_CLK_NODE_T parent);
uint8_t set_parent_ftm2_ext(P_CLK_NODE_T parent);
uint8_t set_parent_ftm3_ext(P_CLK_NODE_T parent);
uint8_t set_parent_ftm0_fix(P_CLK_NODE_T parent);
uint8_t set_parent_ftm1_fix(P_CLK_NODE_T parent);
uint8_t set_parent_ftm2_fix(P_CLK_NODE_T parent);
uint8_t set_parent_ftm3_fix(P_CLK_NODE_T parent);
uint8_t set_parent_nfc(P_CLK_NODE_T parent);
uint8_t set_parent_qspi0(P_CLK_NODE_T parent);
uint8_t set_parent_qspi1(P_CLK_NODE_T parent);
uint8_t set_parent_enet_ext(P_CLK_NODE_T parent);
uint8_t set_parent_enet_rmii(P_CLK_NODE_T parent);
uint8_t set_parent_enet_ts(P_CLK_NODE_T parent);
uint8_t set_parent_esdhc0(P_CLK_NODE_T parent);
uint8_t set_parent_esdhc1(P_CLK_NODE_T parent);
uint8_t set_parent_dcu_pixel0(P_CLK_NODE_T parent);
uint8_t set_parent_dcu_pixel1(P_CLK_NODE_T parent);
uint8_t set_parent_dcu0(P_CLK_NODE_T parent);
uint8_t set_parent_dcu1(P_CLK_NODE_T parent);
uint8_t set_parent_spdif_ext(P_CLK_NODE_T parent);
uint8_t set_parent_esai(P_CLK_NODE_T parent);
uint8_t set_parent_sai0(P_CLK_NODE_T parent);
uint8_t set_parent_sai1(P_CLK_NODE_T parent);
uint8_t set_parent_sai2(P_CLK_NODE_T parent);
uint8_t set_parent_sai3(P_CLK_NODE_T parent);
uint8_t set_parent_video_adc(P_CLK_NODE_T parent);
uint8_t set_parent_gpu(P_CLK_NODE_T parent);
uint8_t set_parent_swo(P_CLK_NODE_T parent);
uint8_t set_parent_trace(P_CLK_NODE_T parent);
uint8_t set_parent_usb0(P_CLK_NODE_T parent);
uint8_t set_parent_usb1(P_CLK_NODE_T parent);
uint8_t set_parent_spdif(P_CLK_NODE_T parent);
uint8_t set_parent_dap(P_CLK_NODE_T parent);
uint8_t set_parent_dma_mux0(P_CLK_NODE_T parent);
uint8_t set_parent_dma_mux1(P_CLK_NODE_T parent);
uint8_t set_parent_dma_mux2(P_CLK_NODE_T parent);
uint8_t set_parent_dma_mux3(P_CLK_NODE_T parent);
uint8_t set_parent_dma0_tcd(P_CLK_NODE_T parent);
uint8_t set_parent_dma1_tcd(P_CLK_NODE_T parent);
uint8_t set_parent_dma0(P_CLK_NODE_T parent);
uint8_t set_parent_dma1(P_CLK_NODE_T parent);
uint8_t set_parent_uart0(P_CLK_NODE_T parent);
uint8_t set_parent_uart1(P_CLK_NODE_T parent);
uint8_t set_parent_uart2(P_CLK_NODE_T parent);
uint8_t set_parent_uart3(P_CLK_NODE_T parent);
uint8_t set_parent_uart4(P_CLK_NODE_T parent);
uint8_t set_parent_uart5(P_CLK_NODE_T parent);
uint8_t set_parent_spi0(P_CLK_NODE_T parent);
uint8_t set_parent_spi1(P_CLK_NODE_T parent);
uint8_t set_parent_spi2(P_CLK_NODE_T parent);
uint8_t set_parent_spi3(P_CLK_NODE_T parent);
uint8_t set_parent_crc(P_CLK_NODE_T parent);
uint8_t set_parent_usbc0(P_CLK_NODE_T parent);
uint8_t set_parent_usbc1(P_CLK_NODE_T parent);
uint8_t set_parent_pdb(P_CLK_NODE_T parent);
uint8_t set_parent_pit(P_CLK_NODE_T parent);
uint8_t set_parent_ftm(P_CLK_NODE_T parent);
uint8_t set_parent_adc0(P_CLK_NODE_T parent);
uint8_t set_parent_adc1(P_CLK_NODE_T parent);
uint8_t set_parent_tcon0(P_CLK_NODE_T parent);
uint8_t set_parent_tcon1(P_CLK_NODE_T parent);
uint8_t set_parent_wdog_a5(P_CLK_NODE_T parent);
uint8_t set_parent_wdog_m4(P_CLK_NODE_T parent);
uint8_t set_parent_lptmr(P_CLK_NODE_T parent);
uint8_t set_parent_rle(P_CLK_NODE_T parent);
uint8_t set_parent_iomuxc(P_CLK_NODE_T parent);
uint8_t set_parent_porta_mult(P_CLK_NODE_T parent);
uint8_t set_parent_portb_mult(P_CLK_NODE_T parent);
uint8_t set_parent_portc_mult(P_CLK_NODE_T parent);
uint8_t set_parent_portd_mult(P_CLK_NODE_T parent);
uint8_t set_parent_porte_mult(P_CLK_NODE_T parent);
uint8_t set_parent_anadig(P_CLK_NODE_T parent);
uint8_t set_parent_scsc(P_CLK_NODE_T parent);
uint8_t set_parent_asrc(P_CLK_NODE_T parent);
uint8_t set_parent_ewm(P_CLK_NODE_T parent);
uint8_t set_parent_i2c0(P_CLK_NODE_T parent);
uint8_t set_parent_i2c1(P_CLK_NODE_T parent);
uint8_t set_parent_i2c2(P_CLK_NODE_T parent);
uint8_t set_parent_i2c3(P_CLK_NODE_T parent);
uint8_t set_parent_wkup(P_CLK_NODE_T parent);
uint8_t set_parent_ccm(P_CLK_NODE_T parent);
uint8_t set_parent_gpc(P_CLK_NODE_T parent);
uint8_t set_parent_vreg_dig(P_CLK_NODE_T parent);
uint8_t set_parent_cmu(P_CLK_NODE_T parent);
uint8_t set_parent_otp(P_CLK_NODE_T parent);
uint8_t set_parent_slcd(P_CLK_NODE_T parent);
uint8_t set_parent_video_decoder(P_CLK_NODE_T parent);
uint8_t set_parent_viu(P_CLK_NODE_T parent);
uint8_t set_parent_dac0(P_CLK_NODE_T parent);
uint8_t set_parent_dac1(P_CLK_NODE_T parent);
uint8_t set_parent_enet_mac_ieee1588_timer0(P_CLK_NODE_T parent);
uint8_t set_parent_enet_mac_ieee1588_timer1(P_CLK_NODE_T parent);
uint8_t set_parent_enet_l2_sw(P_CLK_NODE_T parent);
uint8_t set_parent_mscm(P_CLK_NODE_T parent);
uint8_t set_parent_ca5_scu_gic(P_CLK_NODE_T parent);
uint8_t set_parent_ca5_intd(P_CLK_NODE_T parent);
uint8_t set_parent_ca5_l2c(P_CLK_NODE_T parent);
uint8_t set_parent_nic0(P_CLK_NODE_T parent);
uint8_t set_parent_nic1(P_CLK_NODE_T parent);
uint8_t set_parent_nic2(P_CLK_NODE_T parent);
uint8_t set_parent_nic3(P_CLK_NODE_T parent);
uint8_t set_parent_nic4(P_CLK_NODE_T parent);
uint8_t set_parent_nic5(P_CLK_NODE_T parent);
uint8_t set_parent_nic6(P_CLK_NODE_T parent);
uint8_t set_parent_nic7(P_CLK_NODE_T parent);
uint8_t set_parent_sema4(P_CLK_NODE_T parent);
uint8_t set_parent_ca5_dbg(P_CLK_NODE_T parent);
uint8_t set_parent_ca5_pmu(P_CLK_NODE_T parent);
uint8_t set_parent_ca5_etm(P_CLK_NODE_T parent);
uint8_t set_parent_ca5_romtable(P_CLK_NODE_T parent);
uint8_t set_parent_ca5_cti(P_CLK_NODE_T parent);
uint8_t set_parent_ca5_itm(P_CLK_NODE_T parent);
uint8_t set_parent_ca5_etb(P_CLK_NODE_T parent);
uint8_t set_parent_ca5_funnel(P_CLK_NODE_T parent);
uint8_t set_parent_pltf_tctl(P_CLK_NODE_T parent);
uint8_t set_parent_pltf_tctu(P_CLK_NODE_T parent);
uint8_t set_parent_pltf_funnel(P_CLK_NODE_T parent);
uint8_t set_parent_pltf_swo(P_CLK_NODE_T parent);

uint8_t check_parent_fxosc(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_firc(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_sxosc(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_sirc(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_fast(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_slow(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_clk_24m_irc(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_lprc(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_lfsr(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_pll1(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_pll1_pfd1(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_pll1_pfd2(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_pll1_pfd3(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_pll1_pfd4(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_pll2(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_pll2_pfd1(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_pll2_pfd2(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_pll2_pfd3(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_pll2_pfd4(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_pll3(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_pll3_pfd1(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_pll3_pfd2(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_pll3_pfd3(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_pll3_pfd4(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_pll3_div(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_pll4(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_pll4_div(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_pll5(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_pll5_div(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_pll6(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_pll6_div(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_pll7(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_pll1_pfd(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_pll2_pfd(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_sys(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_ca5_core(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_platform_bus_cm4_core(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_flexbus(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_ips_ipg(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_dramc(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_audio_ext(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_flexcan0(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_flexcan1(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_ftm0_ext(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_ftm1_ext(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_ftm2_ext(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_ftm3_ext(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_ftm0_fix(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_ftm1_fix(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_ftm2_fix(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_ftm3_fix(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_nfc(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_qspi0(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_qspi1(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_enet_ext(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_enet_rmii(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_enet_ts(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_esdhc0(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_esdhc1(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_dcu_pixel0(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_dcu_pixel1(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_dcu0(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_dcu1(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_spdif_ext(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_esai(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_sai0(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_sai1(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_sai2(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_sai3(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_video_adc(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_gpu(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_swo(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_trace(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_usb0(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_usb1(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_spdif(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_dap(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_dma_mux0(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_dma_mux1(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_dma_mux2(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_dma_mux3(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_dma0_tcd(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_dma1_tcd(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_dma0(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_dma1(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_uart0(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_uart1(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_uart2(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_uart3(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_uart4(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_uart5(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_spi0(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_spi1(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_spi2(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_spi3(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_crc(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_usbc0(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_usbc1(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_pdb(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_pit(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_ftm(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_adc0(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_adc1(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_tcon0(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_tcon1(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_wdog_a5(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_wdog_m4(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_lptmr(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_rle(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_iomuxc(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_porta_mult(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_portb_mult(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_portc_mult(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_portd_mult(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_porte_mult(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_anadig(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_scsc(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_asrc(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_ewm(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_i2c0(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_i2c1(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_i2c2(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_i2c3(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_wkup(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_ccm(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_gpc(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_vreg_dig(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_cmu(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_otp(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_slcd(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_video_decoder(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_viu(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_dac0(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_dac1(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_enet_mac_ieee1588_timer0(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_enet_mac_ieee1588_timer1(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_enet_l2_sw(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_mscm(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_ca5_scu_gic(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_ca5_intd(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_ca5_l2c(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_nic0(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_nic1(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_nic2(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_nic3(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_nic4(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_nic5(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_nic6(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_nic7(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_sema4(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_ca5_dbg(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_ca5_pmu(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_ca5_etm(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_ca5_romtable(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_ca5_cti(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_ca5_itm(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_ca5_etb(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_ca5_funnel(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_pltf_tctl(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_pltf_tctu(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_pltf_funnel(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);
uint8_t check_parent_pltf_swo(P_CLK_NODE_T parent, uint8_t* old_open, uint8_t* new_open);

uint8_t open_clk_fxosc(void);
uint8_t open_clk_firc(void);
uint8_t open_clk_sxosc(void);
uint8_t open_clk_sirc(void);
uint8_t open_clk_fxosc_div(void);
uint8_t open_clk_sirc_div(void);
uint8_t open_clk_fast(void);
uint8_t open_clk_slow(void);
uint8_t open_clk_clk_24m_irc(void);
uint8_t open_clk_lprc(void);
uint8_t open_clk_lfsr(void);
uint8_t open_clk_pll1(void);
uint8_t open_clk_pll1_pfd1(void);
uint8_t open_clk_pll1_pfd2(void);
uint8_t open_clk_pll1_pfd3(void);
uint8_t open_clk_pll1_pfd4(void);
uint8_t open_clk_pll2(void);
uint8_t open_clk_pll2_pfd1(void);
uint8_t open_clk_pll2_pfd2(void);
uint8_t open_clk_pll2_pfd3(void);
uint8_t open_clk_pll2_pfd4(void);
uint8_t open_clk_pll3(void);
uint8_t open_clk_pll3_pfd1(void);
uint8_t open_clk_pll3_pfd2(void);
uint8_t open_clk_pll3_pfd3(void);
uint8_t open_clk_pll3_pfd4(void);
uint8_t open_clk_pll3_div(void);
uint8_t open_clk_pll4(void);
uint8_t open_clk_pll4_div(void);
uint8_t open_clk_pll5(void);
uint8_t open_clk_pll5_div(void);
uint8_t open_clk_pll6(void);
uint8_t open_clk_pll6_div(void);
uint8_t open_clk_pll7(void);
uint8_t open_clk_pll1_pfd(void);
uint8_t open_clk_pll2_pfd(void);
uint8_t open_clk_sys(void);
uint8_t open_clk_ca5_core(void);
uint8_t open_clk_platform_bus_cm4_core(void);
uint8_t open_clk_flexbus(void);
uint8_t open_clk_ips_ipg(void);
uint8_t open_clk_dramc(void);
uint8_t open_clk_audio_ext(void);
uint8_t open_clk_flexcan0(void);
uint8_t open_clk_flexcan1(void);
uint8_t open_clk_ftm0_ext(void);
uint8_t open_clk_ftm1_ext(void);
uint8_t open_clk_ftm2_ext(void);
uint8_t open_clk_ftm3_ext(void);
uint8_t open_clk_ftm0_fix(void);
uint8_t open_clk_ftm1_fix(void);
uint8_t open_clk_ftm2_fix(void);
uint8_t open_clk_ftm3_fix(void);
uint8_t open_clk_nfc(void);
uint8_t open_clk_qspi0(void);
uint8_t open_clk_qspi1(void);
uint8_t open_clk_enet_ext(void);
uint8_t open_clk_enet_rmii(void);
uint8_t open_clk_enet_ts(void);
uint8_t open_clk_esdhc0(void);
uint8_t open_clk_esdhc1(void);
uint8_t open_clk_dcu_pixel0(void);
uint8_t open_clk_dcu_pixel1(void);
uint8_t open_clk_dcu0(void);
uint8_t open_clk_dcu1(void);
uint8_t open_clk_spdif_ext(void);
uint8_t open_clk_esai(void);
uint8_t open_clk_sai0(void);
uint8_t open_clk_sai1(void);
uint8_t open_clk_sai2(void);
uint8_t open_clk_sai3(void);
uint8_t open_clk_video_adc(void);
uint8_t open_clk_gpu(void);
uint8_t open_clk_swo(void);
uint8_t open_clk_trace(void);
uint8_t open_clk_usb0(void);
uint8_t open_clk_usb1(void);
uint8_t open_clk_spdif(void);
uint8_t open_clk_dap(void);
uint8_t open_clk_dma_mux0(void);
uint8_t open_clk_dma_mux1(void);
uint8_t open_clk_dma_mux2(void);
uint8_t open_clk_dma_mux3(void);
uint8_t open_clk_dma0_tcd(void);
uint8_t open_clk_dma1_tcd(void);
uint8_t open_clk_dma0(void);
uint8_t open_clk_dma1(void);
uint8_t open_clk_uart0(void);
uint8_t open_clk_uart1(void);
uint8_t open_clk_uart2(void);
uint8_t open_clk_uart3(void);
uint8_t open_clk_uart4(void);
uint8_t open_clk_uart5(void);
uint8_t open_clk_spi0(void);
uint8_t open_clk_spi1(void);
uint8_t open_clk_spi2(void);
uint8_t open_clk_spi3(void);
uint8_t open_clk_crc(void);
uint8_t open_clk_usbc0(void);
uint8_t open_clk_usbc1(void);
uint8_t open_clk_pdb(void);
uint8_t open_clk_pit(void);
uint8_t open_clk_ftm(void);
uint8_t open_clk_adc0(void);
uint8_t open_clk_adc1(void);
uint8_t open_clk_tcon0(void);
uint8_t open_clk_tcon1(void);
uint8_t open_clk_wdog_a5(void);
uint8_t open_clk_wdog_m4(void);
uint8_t open_clk_lptmr(void);
uint8_t open_clk_rle(void);
uint8_t open_clk_iomuxc(void);
uint8_t open_clk_porta_mult(void);
uint8_t open_clk_portb_mult(void);
uint8_t open_clk_portc_mult(void);
uint8_t open_clk_portd_mult(void);
uint8_t open_clk_porte_mult(void);
uint8_t open_clk_anadig(void);
uint8_t open_clk_scsc(void);
uint8_t open_clk_asrc(void);
uint8_t open_clk_ewm(void);
uint8_t open_clk_i2c0(void);
uint8_t open_clk_i2c1(void);
uint8_t open_clk_i2c2(void);
uint8_t open_clk_i2c3(void);
uint8_t open_clk_wkup(void);
uint8_t open_clk_ccm(void);
uint8_t open_clk_gpc(void);
uint8_t open_clk_vreg_dig(void);
uint8_t open_clk_cmu(void);
uint8_t open_clk_otp(void);
uint8_t open_clk_slcd(void);
uint8_t open_clk_video_decoder(void);
uint8_t open_clk_viu(void);
uint8_t open_clk_dac0(void);
uint8_t open_clk_dac1(void);
uint8_t open_clk_enet_mac_ieee1588_timer0(void);
uint8_t open_clk_enet_mac_ieee1588_timer1(void);
uint8_t open_clk_enet_l2_sw(void);
uint8_t open_clk_mscm(void);
uint8_t open_clk_ca5_scu_gic(void);
uint8_t open_clk_ca5_intd(void);
uint8_t open_clk_ca5_l2c(void);
uint8_t open_clk_nic0(void);
uint8_t open_clk_nic1(void);
uint8_t open_clk_nic2(void);
uint8_t open_clk_nic3(void);
uint8_t open_clk_nic4(void);
uint8_t open_clk_nic5(void);
uint8_t open_clk_nic6(void);
uint8_t open_clk_nic7(void);
uint8_t open_clk_sema4(void);
uint8_t open_clk_ca5_dbg(void);
uint8_t open_clk_ca5_pmu(void);
uint8_t open_clk_ca5_etm(void);
uint8_t open_clk_ca5_romtable(void);
uint8_t open_clk_ca5_cti(void);
uint8_t open_clk_ca5_itm(void);
uint8_t open_clk_ca5_etb(void);
uint8_t open_clk_ca5_funnel(void);
uint8_t open_clk_pltf_tctl(void);
uint8_t open_clk_pltf_tctu(void);
uint8_t open_clk_pltf_funnel(void);
uint8_t open_clk_pltf_swo(void);
uint8_t open_clk_enet_ts_ext(void);
uint8_t open_clk_mlb_ext(void);
uint8_t open_clk_esai_ext(void);
uint8_t open_clk_sai0_ext(void);
uint8_t open_clk_sai3_ext(void);
uint8_t open_clk_ftm0(void);
uint8_t open_clk_ftm1(void);
uint8_t open_clk_ftm2(void);
uint8_t open_clk_ftm3(void);

uint8_t close_clk_fxosc(void);
uint8_t close_clk_firc(void);
uint8_t close_clk_sxosc(void);
uint8_t close_clk_sirc(void);
uint8_t close_clk_fxosc_div(void);
uint8_t close_clk_sirc_div(void);
uint8_t close_clk_fast(void);
uint8_t close_clk_slow(void);
uint8_t close_clk_clk_24m_irc(void);
uint8_t close_clk_lprc(void);
uint8_t close_clk_lfsr(void);
uint8_t close_clk_pll1(void);
uint8_t close_clk_pll1_pfd1(void);
uint8_t close_clk_pll1_pfd2(void);
uint8_t close_clk_pll1_pfd3(void);
uint8_t close_clk_pll1_pfd4(void);
uint8_t close_clk_pll2(void);
uint8_t close_clk_pll2_pfd1(void);
uint8_t close_clk_pll2_pfd2(void);
uint8_t close_clk_pll2_pfd3(void);
uint8_t close_clk_pll2_pfd4(void);
uint8_t close_clk_pll3(void);
uint8_t close_clk_pll3_pfd1(void);
uint8_t close_clk_pll3_pfd2(void);
uint8_t close_clk_pll3_pfd3(void);
uint8_t close_clk_pll3_pfd4(void);
uint8_t close_clk_pll3_div(void);
uint8_t close_clk_pll4(void);
uint8_t close_clk_pll4_div(void);
uint8_t close_clk_pll5(void);
uint8_t close_clk_pll5_div(void);
uint8_t close_clk_pll6(void);
uint8_t close_clk_pll6_div(void);
uint8_t close_clk_pll7(void);
uint8_t close_clk_pll1_pfd(void);
uint8_t close_clk_pll2_pfd(void);
uint8_t close_clk_sys(void);
uint8_t close_clk_ca5_core(void);
uint8_t close_clk_platform_bus_cm4_core(void);
uint8_t close_clk_flexbus(void);
uint8_t close_clk_ips_ipg(void);
uint8_t close_clk_dramc(void);
uint8_t close_clk_audio_ext(void);
uint8_t close_clk_flexcan0(void);
uint8_t close_clk_flexcan1(void);
uint8_t close_clk_ftm0_ext(void);
uint8_t close_clk_ftm1_ext(void);
uint8_t close_clk_ftm2_ext(void);
uint8_t close_clk_ftm3_ext(void);
uint8_t close_clk_ftm0_fix(void);
uint8_t close_clk_ftm1_fix(void);
uint8_t close_clk_ftm2_fix(void);
uint8_t close_clk_ftm3_fix(void);
uint8_t close_clk_nfc(void);
uint8_t close_clk_qspi0(void);
uint8_t close_clk_qspi1(void);
uint8_t close_clk_enet_ext(void);
uint8_t close_clk_enet_rmii(void);
uint8_t close_clk_enet_ts(void);
uint8_t close_clk_esdhc0(void);
uint8_t close_clk_esdhc1(void);
uint8_t close_clk_dcu_pixel0(void);
uint8_t close_clk_dcu_pixel1(void);
uint8_t close_clk_dcu0(void);
uint8_t close_clk_dcu1(void);
uint8_t close_clk_spdif_ext(void);
uint8_t close_clk_esai(void);
uint8_t close_clk_sai0(void);
uint8_t close_clk_sai1(void);
uint8_t close_clk_sai2(void);
uint8_t close_clk_sai3(void);
uint8_t close_clk_video_adc(void);
uint8_t close_clk_gpu(void);
uint8_t close_clk_swo(void);
uint8_t close_clk_trace(void);
uint8_t close_clk_usb0(void);
uint8_t close_clk_usb1(void);
uint8_t close_clk_spdif(void);
uint8_t close_clk_dap(void);
uint8_t close_clk_dma_mux0(void);
uint8_t close_clk_dma_mux1(void);
uint8_t close_clk_dma_mux2(void);
uint8_t close_clk_dma_mux3(void);
uint8_t close_clk_dma0_tcd(void);
uint8_t close_clk_dma1_tcd(void);
uint8_t close_clk_dma0(void);
uint8_t close_clk_dma1(void);
uint8_t close_clk_uart0(void);
uint8_t close_clk_uart1(void);
uint8_t close_clk_uart2(void);
uint8_t close_clk_uart3(void);
uint8_t close_clk_uart4(void);
uint8_t close_clk_uart5(void);
uint8_t close_clk_spi0(void);
uint8_t close_clk_spi1(void);
uint8_t close_clk_spi2(void);
uint8_t close_clk_spi3(void);
uint8_t close_clk_crc(void);
uint8_t close_clk_usbc0(void);
uint8_t close_clk_usbc1(void);
uint8_t close_clk_pdb(void);
uint8_t close_clk_pit(void);
uint8_t close_clk_ftm(void);
uint8_t close_clk_adc0(void);
uint8_t close_clk_adc1(void);
uint8_t close_clk_tcon0(void);
uint8_t close_clk_tcon1(void);
uint8_t close_clk_wdog_a5(void);
uint8_t close_clk_wdog_m4(void);
uint8_t close_clk_lptmr(void);
uint8_t close_clk_rle(void);
uint8_t close_clk_iomuxc(void);
uint8_t close_clk_porta_mult(void);
uint8_t close_clk_portb_mult(void);
uint8_t close_clk_portc_mult(void);
uint8_t close_clk_portd_mult(void);
uint8_t close_clk_porte_mult(void);
uint8_t close_clk_anadig(void);
uint8_t close_clk_scsc(void);
uint8_t close_clk_asrc(void);
uint8_t close_clk_ewm(void);
uint8_t close_clk_i2c0(void);
uint8_t close_clk_i2c1(void);
uint8_t close_clk_i2c2(void);
uint8_t close_clk_i2c3(void);
uint8_t close_clk_wkup(void);
uint8_t close_clk_ccm(void);
uint8_t close_clk_gpc(void);
uint8_t close_clk_vreg_dig(void);
uint8_t close_clk_cmu(void);
uint8_t close_clk_otp(void);
uint8_t close_clk_slcd(void);
uint8_t close_clk_video_decoder(void);
uint8_t close_clk_viu(void);
uint8_t close_clk_dac0(void);
uint8_t close_clk_dac1(void);
uint8_t close_clk_enet_mac_ieee1588_timer0(void);
uint8_t close_clk_enet_mac_ieee1588_timer1(void);
uint8_t close_clk_enet_l2_sw(void);
uint8_t close_clk_mscm(void);
uint8_t close_clk_ca5_scu_gic(void);
uint8_t close_clk_ca5_intd(void);
uint8_t close_clk_ca5_l2c(void);
uint8_t close_clk_nic0(void);
uint8_t close_clk_nic1(void);
uint8_t close_clk_nic2(void);
uint8_t close_clk_nic3(void);
uint8_t close_clk_nic4(void);
uint8_t close_clk_nic5(void);
uint8_t close_clk_nic6(void);
uint8_t close_clk_nic7(void);
uint8_t close_clk_sema4(void);
uint8_t close_clk_ca5_dbg(void);
uint8_t close_clk_ca5_pmu(void);
uint8_t close_clk_ca5_etm(void);
uint8_t close_clk_ca5_romtable(void);
uint8_t close_clk_ca5_cti(void);
uint8_t close_clk_ca5_itm(void);
uint8_t close_clk_ca5_etb(void);
uint8_t close_clk_ca5_funnel(void);
uint8_t close_clk_pltf_tctl(void);
uint8_t close_clk_pltf_tctu(void);
uint8_t close_clk_pltf_funnel(void);
uint8_t close_clk_pltf_swo(void);
uint8_t close_clk_enet_ts_ext(void);
uint8_t close_clk_mlb_ext(void);
uint8_t close_clk_esai_ext(void);
uint8_t close_clk_sai0_ext(void);
uint8_t close_clk_sai3_ext(void);
uint8_t close_clk_ftm0(void);
uint8_t close_clk_ftm1(void);
uint8_t close_clk_ftm2(void);
uint8_t close_clk_ftm3(void);


uint8_t calc_freq_general(P_CLK_NODE_T p_self, uint32_t parent_freq);
uint8_t calc_freq_fxosc(P_CLK_NODE_T p_self, uint32_t parent_freq);
uint8_t calc_freq_firc(P_CLK_NODE_T p_self, uint32_t parent_freq);
uint8_t calc_freq_sxosc(P_CLK_NODE_T p_self, uint32_t parent_freq);
uint8_t calc_freq_sirc(P_CLK_NODE_T p_self, uint32_t parent_freq);
uint8_t calc_freq_fxosc_div(P_CLK_NODE_T p_self, uint32_t parent_freq);
uint8_t calc_freq_sirc_div(P_CLK_NODE_T p_self, uint32_t parent_freq);
uint8_t calc_freq_lprc(P_CLK_NODE_T p_self, uint32_t parent_freq);
uint8_t calc_freq_lfsr(P_CLK_NODE_T p_self, uint32_t parent_freq);
uint8_t calc_freq_pll1(P_CLK_NODE_T p_self, uint32_t parent_freq);
uint8_t calc_freq_pll1_pfd1(P_CLK_NODE_T p_self, uint32_t parent_freq);
uint8_t calc_freq_pll1_pfd2(P_CLK_NODE_T p_self, uint32_t parent_freq);
uint8_t calc_freq_pll1_pfd3(P_CLK_NODE_T p_self, uint32_t parent_freq);
uint8_t calc_freq_pll1_pfd4(P_CLK_NODE_T p_self, uint32_t parent_freq);
uint8_t calc_freq_pll2(P_CLK_NODE_T p_self, uint32_t parent_freq);
uint8_t calc_freq_pll2_pfd1(P_CLK_NODE_T p_self, uint32_t parent_freq);
uint8_t calc_freq_pll2_pfd2(P_CLK_NODE_T p_self, uint32_t parent_freq);
uint8_t calc_freq_pll2_pfd3(P_CLK_NODE_T p_self, uint32_t parent_freq);
uint8_t calc_freq_pll2_pfd4(P_CLK_NODE_T p_self, uint32_t parent_freq);
uint8_t calc_freq_pll3(P_CLK_NODE_T p_self, uint32_t parent_freq);
uint8_t calc_freq_pll3_pfd1(P_CLK_NODE_T p_self, uint32_t parent_freq);
uint8_t calc_freq_pll3_pfd2(P_CLK_NODE_T p_self, uint32_t parent_freq);
uint8_t calc_freq_pll3_pfd3(P_CLK_NODE_T p_self, uint32_t parent_freq);
uint8_t calc_freq_pll3_pfd4(P_CLK_NODE_T p_self, uint32_t parent_freq);
uint8_t calc_freq_pll3_div(P_CLK_NODE_T p_self, uint32_t parent_freq);
uint8_t calc_freq_pll4(P_CLK_NODE_T p_self, uint32_t parent_freq);
uint8_t calc_freq_pll4_div(P_CLK_NODE_T p_self, uint32_t parent_freq);
uint8_t calc_freq_pll5(P_CLK_NODE_T p_self, uint32_t parent_freq);
uint8_t calc_freq_pll5_div(P_CLK_NODE_T p_self, uint32_t parent_freq);
uint8_t calc_freq_pll6(P_CLK_NODE_T p_self, uint32_t parent_freq);
uint8_t calc_freq_pll6_div(P_CLK_NODE_T p_self, uint32_t parent_freq);
uint8_t calc_freq_pll7(P_CLK_NODE_T p_self, uint32_t parent_freq);
uint8_t calc_freq_ca5_core(P_CLK_NODE_T p_self, uint32_t parent_freq);
uint8_t calc_freq_platform_bus_cm4_core(P_CLK_NODE_T p_self, uint32_t parent_freq);
uint8_t calc_freq_flexbus(P_CLK_NODE_T p_self, uint32_t parent_freq);
uint8_t calc_freq_ips_ipg(P_CLK_NODE_T p_self, uint32_t parent_freq);
uint8_t calc_freq_nfc(P_CLK_NODE_T p_self, uint32_t parent_freq);
uint8_t calc_freq_qspi0(P_CLK_NODE_T p_self, uint32_t parent_freq);
uint8_t calc_freq_qspi1(P_CLK_NODE_T p_self, uint32_t parent_freq);
uint8_t calc_freq_esdhc0(P_CLK_NODE_T p_self, uint32_t parent_freq);
uint8_t calc_freq_esdhc1(P_CLK_NODE_T p_self, uint32_t parent_freq);
uint8_t calc_freq_dcu_pixel0(P_CLK_NODE_T p_self, uint32_t parent_freq);
uint8_t calc_freq_dcu_pixel1(P_CLK_NODE_T p_self, uint32_t parent_freq);
uint8_t calc_freq_esai(P_CLK_NODE_T p_self, uint32_t parent_freq);
uint8_t calc_freq_sai0(P_CLK_NODE_T p_self, uint32_t parent_freq);
uint8_t calc_freq_sai1(P_CLK_NODE_T p_self, uint32_t parent_freq);
uint8_t calc_freq_sai2(P_CLK_NODE_T p_self, uint32_t parent_freq);
uint8_t calc_freq_sai3(P_CLK_NODE_T p_self, uint32_t parent_freq);
uint8_t calc_freq_video_adc(P_CLK_NODE_T p_self, uint32_t parent_freq);
uint8_t calc_freq_swo(P_CLK_NODE_T p_self, uint32_t parent_freq);
uint8_t calc_freq_trace(P_CLK_NODE_T p_self, uint32_t parent_freq);
uint8_t calc_freq_spdif(P_CLK_NODE_T p_self, uint32_t parent_freq);

uint8_t set_freq_na(P_CLK_NODE_T p_self, va_list args, uint8_t* old_val, uint8_t* new_val);
uint8_t set_freq_lprc(P_CLK_NODE_T p_self, va_list args, uint8_t* old_val, uint8_t* new_val);
uint8_t set_freq_pll1(P_CLK_NODE_T p_self, va_list args, uint8_t* old_val, uint8_t* new_val);
uint8_t set_freq_qspi0(P_CLK_NODE_T p_self, va_list args, uint8_t* old_val, uint8_t* new_val);
uint8_t set_freq_qspi1(P_CLK_NODE_T p_self, va_list args, uint8_t* old_val, uint8_t* new_val);
uint8_t set_freq_pll1_pfd1(P_CLK_NODE_T p_self, va_list args, uint8_t* old_val, uint8_t* new_val);
uint8_t set_freq_pll1_pfd2(P_CLK_NODE_T p_self, va_list args, uint8_t* old_val, uint8_t* new_val);
uint8_t set_freq_pll1_pfd3(P_CLK_NODE_T p_self, va_list args, uint8_t* old_val, uint8_t* new_val);
uint8_t set_freq_pll1_pfd4(P_CLK_NODE_T p_self, va_list args, uint8_t* old_val, uint8_t* new_val);
uint8_t set_freq_pll2(P_CLK_NODE_T p_self, va_list args, uint8_t* old_val, uint8_t* new_val);
uint8_t set_freq_pll2_pfd1(P_CLK_NODE_T p_self, va_list args, uint8_t* old_val, uint8_t* new_val);
uint8_t set_freq_pll2_pfd2(P_CLK_NODE_T p_self, va_list args, uint8_t* old_val, uint8_t* new_val);
uint8_t set_freq_pll2_pfd3(P_CLK_NODE_T p_self, va_list args, uint8_t* old_val, uint8_t* new_val);
uint8_t set_freq_pll2_pfd4(P_CLK_NODE_T p_self, va_list args, uint8_t* old_val, uint8_t* new_val);
uint8_t set_freq_pll3(P_CLK_NODE_T p_self, va_list args, uint8_t* old_val, uint8_t* new_val);
uint8_t set_freq_pll3_pfd1(P_CLK_NODE_T p_self, va_list args, uint8_t* old_val, uint8_t* new_val);
uint8_t set_freq_pll3_pfd2(P_CLK_NODE_T p_self, va_list args, uint8_t* old_val, uint8_t* new_val);
uint8_t set_freq_pll3_pfd3(P_CLK_NODE_T p_self, va_list args, uint8_t* old_val, uint8_t* new_val);
uint8_t set_freq_pll3_pfd4(P_CLK_NODE_T p_self, va_list args, uint8_t* old_val, uint8_t* new_val);
uint8_t set_freq_pll3_div(P_CLK_NODE_T p_self, va_list args, uint8_t* old_val, uint8_t* new_val);
uint8_t set_freq_pll4(P_CLK_NODE_T p_self, va_list args, uint8_t* old_val, uint8_t* new_val);
uint8_t set_freq_pll4_div(P_CLK_NODE_T p_self, va_list args, uint8_t* old_val, uint8_t* new_val);
uint8_t set_freq_pll6(P_CLK_NODE_T p_self, va_list args, uint8_t* old_val, uint8_t* new_val);
uint8_t set_freq_pll6_div(P_CLK_NODE_T p_self, va_list args, uint8_t* old_val, uint8_t* new_val);
uint8_t set_freq_pll7(P_CLK_NODE_T p_self, va_list args, uint8_t* old_val, uint8_t* new_val);
uint8_t set_freq_ca5_core(P_CLK_NODE_T p_self, va_list args, uint8_t* old_val, uint8_t* new_val);
uint8_t set_freq_platform_bus_cm4_core(P_CLK_NODE_T p_self, va_list args, uint8_t* old_val, uint8_t* new_val);
uint8_t set_freq_flexbus(P_CLK_NODE_T p_self, va_list args, uint8_t* old_val, uint8_t* new_val);
uint8_t set_freq_ips_ipg(P_CLK_NODE_T p_self, va_list args, uint8_t* old_val, uint8_t* new_val);
uint8_t set_freq_nfc(P_CLK_NODE_T p_self, va_list args, uint8_t* old_val, uint8_t* new_val);
uint8_t set_freq_esdhc0(P_CLK_NODE_T p_self, va_list args, uint8_t* old_val, uint8_t* new_val);
uint8_t set_freq_esdhc1(P_CLK_NODE_T p_self, va_list args, uint8_t* old_val, uint8_t* new_val);
uint8_t set_freq_dcu_pixel0(P_CLK_NODE_T p_self, va_list args, uint8_t* old_val, uint8_t* new_val);
uint8_t set_freq_dcu_pixel1(P_CLK_NODE_T p_self, va_list args, uint8_t* old_val, uint8_t* new_val);
uint8_t set_freq_esai(P_CLK_NODE_T p_self, va_list args, uint8_t* old_val, uint8_t* new_val);
uint8_t set_freq_sai0(P_CLK_NODE_T p_self, va_list args, uint8_t* old_val, uint8_t* new_val);
uint8_t set_freq_sai1(P_CLK_NODE_T p_self, va_list args, uint8_t* old_val, uint8_t* new_val);
uint8_t set_freq_sai2(P_CLK_NODE_T p_self, va_list args, uint8_t* old_val, uint8_t* new_val);
uint8_t set_freq_sai3(P_CLK_NODE_T p_self, va_list args, uint8_t* old_val, uint8_t* new_val);
uint8_t set_freq_video_adc(P_CLK_NODE_T p_self, va_list args, uint8_t* old_val, uint8_t* new_val);
uint8_t set_freq_swo(P_CLK_NODE_T p_self, va_list args, uint8_t* old_val, uint8_t* new_val);
uint8_t set_freq_trace(P_CLK_NODE_T p_self, va_list args, uint8_t* old_val, uint8_t* new_val);
uint8_t set_freq_spdif(P_CLK_NODE_T p_self, va_list args, uint8_t* old_val, uint8_t* new_val);

uint8_t dump_possible_parent_fast(void);
uint8_t dump_possible_parent_slow(void);
uint8_t dump_possible_parent_clk_24m_irc(void);
uint8_t dump_possible_parent_pll1_pfd(void);
uint8_t dump_possible_parent_pll2_pfd(void);
uint8_t dump_possible_parent_sys(void);
uint8_t dump_possible_parent_dramc(void);
uint8_t dump_possible_parent_flexcan(void);
uint8_t dump_possible_parent_ftm0_ext(void);
uint8_t dump_possible_parent_ftm0_fix(void);
uint8_t dump_possible_parent_nfc(void);
uint8_t dump_possible_parent_qspi(void);
uint8_t dump_possible_parent_enet_rmii(void);
uint8_t dump_possible_parent_enet_ts(void);
uint8_t dump_possible_parent_esdhc(void);
uint8_t dump_possible_parent_dcu_pixel(void);
uint8_t dump_possible_parent_esai(void);
uint8_t dump_possible_parent_sai(void);
uint8_t dump_possible_parent_video_adc(void);
uint8_t dump_possible_parent_gpu(void);
uint8_t dump_possible_parent_swo(void);
uint8_t dump_possible_parent_trace(void);
uint8_t dump_possible_parent_spdif(void);
uint8_t dump_possible_parent_ftm(void);
uint8_t dump_possible_parent_ftm_ext(void);
uint8_t dump_possible_parent_ftm_fix(void);

uint8_t open_clk(P_CLK_NODE_T p_clk);
uint8_t close_clk(P_CLK_NODE_T p_clk);
void open_clk_postproc(P_CLK_NODE_T p_clk);
void close_clk_preproc(P_CLK_NODE_T p_clk);


#endif
